package Classwork.Unit2.NavigationLab;

/**
 * NavigationLab - A route planning and optimization system
 *
 * Main class that serves as the entry point for the navigation lab application.
 * This class contains the main method to test and demonstrate route planning
 * functionality.
 *
 * @author Afraz Sohail
 * @version final
 * @since 1.0
 *
 *        Javadoc documentation generated by Claude Sonnet 4
 */
public class Tester {
    /**
     * Main method that serves as the entry point for the NavigationLab application.
     * Used to test and demonstrate route planning, optimization, and navigation
     * functionality.
     *
     * @param args Command line arguments (not currently used)
     */
    public static void main(String args[]) {
        Route fnaf = new Route();
        System.out.println(fnaf);

        fnaf.addLocation(new Location("Freddy Fazbear's Pizza", 3, 4, null));
        fnaf.addLocation(new Location("Bonnie's Stage", 5, 6, null));
        fnaf.addLocation(new Location("Chica's Kitchen", 7, 8, null));
        fnaf.addLocation(new Location("Foxy's Cove", 1, 6, null));
        System.out.println(fnaf);

        fnaf.swap(new Location("Foxy's Cove", 1, 6, null), new Location("Chica's Kitchen", 1, 6, null));
        System.out.println(fnaf);
    }
}
