import Location;

package Classwork;

/**
 * NavigationLab - A route planning and optimization system
 *
 * This class represents a route consisting of locations connected in a linked
 * list structure.
 * The route always starts and ends at a depot location. It provides
 * functionality to add/remove
 * locations, calculate total distance, reverse the route, and perform route
 * optimizations.
 *
 * @author Afraz Sohail
 * @version final
 * @since 1.0
 *
 *        Javadoc documentation generated by Claude Sonnet 4
 */
public class Route {
    /** The starting and ending point of the route, located at coordinates (0,0) */
    Location depot;
    /** The current location being processed or visited in the route */
    Location currentLocation;

    /**
     * Default constructor that creates an empty route with only a depot location.
     * The depot is positioned at coordinates (0,0) and serves as both start and end
     * point.
     */
    public Route() {
        this.depot = new Location("Depot", 0, 0, null);
        this.currentLocation = depot;
    }

    /**
     * Constructor that creates a route with a depot and adds the specified location
     * to the route.
     *
     * @param newLocation The first location to add to the route after the depot
     */
    public Route(Location newLocation) {
        this();
        addLocation(newLocation);
    }

    /**
     * Calculates the total distance of the complete route.
     * The route distance includes the path from depot through all locations and
     * back to depot.
     *
     * @return The total Euclidean distance of the route, or 0.0 if the route is
     *         empty
     */
    public double routeDistance() {
        if (depot == null || depot.next == null) {
            return 0.0d;
        }

        Location runner = depot;
        double routeDistance = 0.0d;
        while (runner.next != null) {
            routeDistance += runner.distanceTo(runner.next);
            runner = runner.next;
        }
        routeDistance += runner.distanceTo(depot);

        return routeDistance;
    }

    /**
     * Reverses the order of locations in the route (excluding the depot).
     * The depot remains as the starting point, but all other locations are visited
     * in reverse order.
     * If the route has fewer than 2 locations after the depot, no action is taken.
     */
    public void reverseRoute() {
        if (depot == null || depot.next == null || depot.next.next == null) {
            return;
        }

        Location previous = null;
        Location current = depot.next;
        Location next = null;

        Location last = depot;

        do {
            next = current.next;
            current.next = previous;
            previous = current;
            current = next;
            last = previous;
        } while (current != null);

        depot.next = last;
    }

    /**
     * Adds a new location to the end of the route.
     * The location is appended after the last location in the current route.
     *
     * @param newLocation The location to add to the route
     * @return true if the location was successfully added, false if newLocation is
     *         null
     */
    public boolean addLocation(Location newLocation) {
        if (newLocation == null) {
            return false;
        }

        if (depot == null) {
            depot = newLocation;
            return true;
        }

        Location runner = depot;
        while (runner.next != null) {
            runner = runner.next;
        }
        runner.next = newLocation;

        return true;
    }

    /**
     * Inserts a new location at the specified index in the route.
     * If index is 0, the location becomes the new depot.
     * All locations at or after the specified index are shifted one position
     * forward.
     *
     * @param index       The position where the new location should be inserted
     *                    (0-based)
     * @param newLocation The location to add to the route
     * @return true if the location was successfully added, false if newLocation is
     *         null or index is invalid
     */
    public boolean addLocation(int index, Location newLocation) {
        if (newLocation == null) {
            return false;
        }

        if (index == 0) {
            newLocation.next = depot;
            depot = newLocation;
            return true;
        }

        Location runner = depot;
        for (int i = 1; i < index; i++) {
            runner = runner.next;

            if (runner == null) {
                return false;
            }
        }

        newLocation.next = runner.next;
        runner.next = newLocation;
        return true;
    }

    /**
     * Removes all locations with the same name as the specified location from the
     * route.
     * This method removes all occurrences of locations that match the name of the
     * given location.
     * The depot cannot be removed using this method.
     *
     * @param location The location whose name is used to identify locations to
     *                 remove
     * @return true if at least one location was removed, false if location is null,
     *         depot is null, or no matching locations found
     */
    public boolean removeLocation(Location location) {
        if (location == null || depot == null) {
            return false;
        }

        boolean hasRemoved = false;

        Location runner = depot;
        while (runner.next != null) {
            if (runner.next.name == location.name) {
                runner.next = runner.next.next;
                hasRemoved = true;
            } else {
                runner = runner.next;
            }
        }

        return hasRemoved;
    }

    /**
     * Removes the location at the specified index from the route.
     * If index is 0, the depot is replaced by the next location in the route.
     *
     * @param index The index of the location to remove (0-based)
     * @return true if the location was successfully removed, false if index is
     *         invalid or depot is null
     */
    public boolean removeLocation(int index) {
        if (index < 0 || depot == null) {
            return false;
        }

        if (index == 0) {
            depot = depot.next;
            return true;
        }

        Location runner = depot;
        for (int i = 1; i < index; i++) {
            runner = runner.next;
            if (runner == null) {
                return false;
            }
        }

        runner.next = runner.next.next;
        return true;
    }

    /**
     * Replaces the location at the specified index with a new location.
     * The new location maintains the same position in the route sequence.
     *
     * @param index       The index of the location to replace (0-based)
     * @param newLocation The new location to place at the specified index
     * @return true if the location was successfully replaced, false if newLocation
     *         is null or index is invalid
     */
    public boolean setLocation(int index, Location newLocation) {
        if (newLocation == null) {
            return false;
        }

        if (index == 0) {
            newLocation.next = depot.next;
            depot = newLocation;
            return true;
        }

        Location runner = depot;
        for (int i = 1; i < index; i++) {
            runner = runner.next;
            if (runner == null) {
                return false;
            }
        }

        if (runner.next != null) {
            newLocation.next = runner.next.next;
        }
        runner.next = newLocation;
        return true;
    }

    /**
     * Finds the longest distance between consecutive locations in the route.
     * This includes the distance from the last location back to the depot.
     *
     * @return The longest distance between any two consecutive locations in the
     *         route, or 0.0 if the route is empty
     */
    public double longestLeg() {
        if (depot == null || depot.next == null) {
            return 0.0d;
        }

        Location runner = depot;
        double longestLeg = 0.0d;
        while (runner.next != null) {
            if (runner.distanceTo(runner.next) > longestLeg) {
                longestLeg = runner.distanceTo(runner.next);
            }

            runner = runner.next;
        }
        if (runner.distanceTo(depot) > longestLeg) {
            longestLeg = runner.distanceTo(depot);
        }

        return longestLeg;
    }

    /**
     * Swaps the positions of two locations in the route.
     * The locations are identified by their names and their positions in the route
     * are exchanged.
     *
     * @param location1 The first location to swap
     * @param location2 The second location to swap
     * @return true if the swap was successful, false if depot is null, locations
     *         have the same name, or either location is not found in the route
     */
    public boolean swap(Location location1, Location location2) {
        if (depot == null || location1.name == location2.name) {
            return false;
        }

        Location driver1 = depot;
        while (driver1.next != null && driver1.next.name != location1.name) {
            driver1 = driver1.next;
        }
        if (driver1.next.name != location1.name) {
            return false;
        }

        Location driver2 = depot;
        while (driver2.next != null && driver2.next.name != location2.name) {
            driver2 = driver2.next;
        }
        if (driver2.next.name != location2.name) {
            return false;
        }

        Location previousLocation1 = driver1;
        Location previousLocation2 = driver2;

        Location nextLocation1 = (driver1.next.next != null) ? driver1.next.next : null;
        Location nextLocation2 = (driver2.next.next != null) ? driver2.next.next : null;

        location1.next = nextLocation2;
        location2.next = nextLocation1;

        previousLocation1.next = location2;
        previousLocation2.next = location1;

        return true;
    }

    /**
     * Returns a string representation of the complete route.
     * The string shows all locations in order, connected by arrows, ending back at
     * the depot.
     * Format: "depot -> location1 -> location2 -> ... -> depot"
     *
     * @return A string representation of the route showing the path from depot
     *         through all locations and back to depot
     */
    @Override
    public String toString() {
        Location driver = depot;
        String routeString = "";
        while (driver != null) {
            routeString += driver.name + " (" + driver.x + ", " + driver.y + ") -> ";
            driver = driver.next;
        }
        return routeString + depot.name + " (" + depot.x + ", " + depot.y + ") ";
    }

    // Basic Linked List Methods

    /**
     * Returns the number of locations in the route, including the depot.
     *
     * @return The total number of locations in the route (depot + all other
     *         locations)
     */
    public int size() {
        int size = 0;
        Location runner = depot;
        while (runner != null) {
            size++;
            runner = runner.next;
        }
        return size;
    }

    /**
     * Retrieves the location at the specified index in the route.
     * Index 0 returns the depot, index 1 returns the first location after depot,
     * etc.
     *
     * @param index The index of the location to retrieve (0-based)
     * @return The location at the specified index, or null if index is invalid or
     *         out of bounds
     */
    public Location get(int index) {
        if (index < 0 || depot == null) {
            return null;
        }

        Location runner = depot;
        for (int i = 0; i < index; i++) {
            runner = runner.next;
            if (runner == null) {
                return null;
            }
        }
        return runner;
    }

    /**
     * Checks if the route is completely empty (no depot or other locations).
     *
     * @return true if the route has no locations at all, false otherwise
     */
    public boolean isEmpty() {
        return depot == null;
    }

    /**
     * Removes all locations from the route, including the depot.
     * After calling this method, the route will be completely empty.
     */
    public void clear() {
        depot = null;
    }

    /**
     * Returns the first location in the route (the depot).
     *
     * @return The depot location, or null if the route is empty
     */
    public Location getFirst() {
        return depot;
    }

    /**
     * Returns the last location in the route.
     * This is the location that connects back to the depot to complete the circuit.
     *
     * @return The last location in the route, or null if the route is empty
     */
    public Location getLast() {
        if (depot == null) {
            return null;
        }

        Location runner = depot;
        while (runner.next != null) {
            runner = runner.next;
        }
        return runner;
    }

    /**
     * Finds the index of the first occurrence of a location with the same name as
     * the specified location.
     * The search is performed by comparing location names.
     *
     * @param location The location to search for (comparison is done by name)
     * @return The index of the first matching location, or -1 if not found or if
     *         location is null
     */
    public int indexOf(Location location) {
        if (location == null || depot == null) {
            return -1;
        }

        Location runner = depot;
        int index = 0;
        while (runner != null) {
            if (runner.name == location.name) {
                return index;
            }
            runner = runner.next;
            index++;
        }
        return -1;
    }
}
