package Classwork.Unit3.CustomHashmap.KEV;

/*
 * Entry.java
 *
 * Represents a single node (entry) in the custom hash map, supporting chaining for collision resolution.
 * Contains references to the key, value, and neighboring entries in the chain.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

/**
 * Entry represents a key-value pair in the hash map, with links to previous and
 * next entries for chaining.
 */
public class Entry {
    /**
     * The key for this entry.
     */
    public Key key;

    /**
     * The value associated with the key.
     */
    public Value value;

    /**
     * Reference to the previous entry in the chain (if any).
     */
    public Entry prev;

    /**
     * Reference to the next entry in the chain (if any).
     */
    public Entry next;

    /**
     * Constructs an Entry with the given key and value.
     *
     * @param key   the key for this entry
     * @param value the value associated with the key
     */
    public Entry(Key key, Value value) {
        this.key = key;
        this.value = value;
    }

    /**
     * Returns a string representation of the entry (key and value).
     *
     * @return string representation
     */
    @Override
    public String toString() {
        return key + "\t" + value;
    }
}
