package Classwork.Unit3.CustomHashmap.KEV;

/*
 * Key.java
 *
 * Represents the key for entries in the custom hash map, consisting of a district name and code.
 * Provides methods for equality, hashing, and string representation.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

/**
 * Key represents a unique identifier for hash map entries, using district name
 * and code.
 */
public class Key {
    /**
     * The name of the district.
     */
    private String districtName;

    /**
     * Returns the district name.
     *
     * @return district name
     */
    public String getName() {
        return districtName;
    }

    /**
     * The code of the district.
     */
    private int districtCode;

    /**
     * Returns the district code.
     *
     * @return district code
     */
    public int getCode() {
        return districtCode;
    }

    /**
     * Constructs a Key with the given district name and code.
     *
     * @param districtName the name of the district
     * @param districtCode the code of the district
     */
    public Key(String districtName, int districtCode) {
        this.districtName = districtName;
        this.districtCode = districtCode;
    }

    /**
     * Returns the hash code for this key (based on district code).
     *
     * @return hash code
     */
    @Override
    public int hashCode() {
        return districtCode;
    }

    /**
     * Returns a string representation of the key.
     *
     * @return string representation
     */
    @Override
    public String toString() {
        return "#" + districtCode + "\t" + districtName + "\n";
    }

    /**
     * Checks if this key is equal to another object.
     *
     * @param object the object to compare
     * @return true if equal, false otherwise
     */
    @Override
    public boolean equals(Object object) {
        if (this == object)
            return true;
        if (object == null)
            return false;
        if (getClass() != object.getClass())
            return false;
        Key keyObject = (Key) object;
        if (districtCode != (keyObject.getCode()))
            return false;
        if (districtName == null) {
            if (keyObject.districtName != null)
                return false;
        } else if (!districtName.equals(keyObject.getName()))
            return false;
        return true;
    }
}
