package Classwork.Unit3.CustomHashmap.KEV;

/*
 * LanguageData.java
 *
 * Represents a language and its number of speakers for a given state or region.
 * Provides methods for accessing language name, speaker count, and formatted string output.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

/**
 * LanguageData stores the name of a language and the number of speakers.
 */
public class LanguageData {
    /**
     * The name of the language.
     */
    private String name;

    /**
     * Returns the name of the language.
     *
     * @return language name
     */
    public String getName() {
        return name;
    }

    /**
     * The number of speakers for this language.
     */
    private int speakers;

    /**
     * Returns the number of speakers.
     *
     * @return number of speakers
     */
    public int getSpeakers() {
        return speakers;
    }

    /**
     * Constructs a LanguageData object with the given name and speaker count.
     *
     * @param name     the language name
     * @param speakers the number of speakers
     */
    public LanguageData(String name, int speakers) {
        this.name = name;
        this.speakers = speakers;
    }

    /**
     * Returns a formatted string representation of the language and speaker count.
     * Uses Indian number system shortcuts (Cr, L, K).
     *
     * @return formatted string
     */
    @Override
    public String toString() {
        if (name == null)
            return null;

        String spkrOutput = "";

        if (speakers >= 1_00_00_000) {
            int num = speakers / 1_00_000;
            spkrOutput = (num / 100.0) + "Cr";
        } else if (speakers >= 1_00_000) {
            int num = speakers / 1_000;
            spkrOutput = (num / 100.0) + "L";
        } else if (speakers >= 1_000) {
            int num = speakers / 10;
            spkrOutput = (num / 100.0) + "K";
        } else {
            spkrOutput = Integer.toString(speakers);
        }
        return name + " (" + spkrOutput + " speakers)";
    }
}
