package Classwork.Unit3.CustomHashmap.KEV;

/*
 * Value.java
 *
 * Represents the value for a hash map entry, containing a state name and an array of languages spoken in that state.
 * Provides methods for cloning, construction, and string representation.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

/**
 * Value stores the state name and an array of LanguageData objects for a hash
 * map entry.
 */
public class Value {
    /**
     * The name of the state.
     */
    public String stateName;

    /**
     * Array of languages spoken in the state (up to 3).
     */
    public LanguageData[] listOfLanguages = new LanguageData[3];

    /**
     * Returns a deep clone of this Value object.
     *
     * @return a new Value object with the same data
     */
    public Value getClone() {
        String inits[] = new String[listOfLanguages.length * 2];
        for (int i = 0; i < listOfLanguages.length; i++) {
            inits[i * 2] = listOfLanguages[i].getName();
            inits[i * 2 + 1] = Integer.toString(listOfLanguages[i].getSpeakers());
        }
        return new Value(stateName, inits);
    }

    /**
     * Constructs a Value with a state name and three languages.
     *
     * @param stateName the name of the state
     * @param lang1     first language
     * @param spkr1     speakers of first language
     * @param lang2     second language
     * @param spkr2     speakers of second language
     * @param lang3     third language
     * @param spkr3     speakers of third language
     */
    public Value(String stateName, String lang1, int spkr1, String lang2, int spkr2, String lang3, int spkr3) {
        this.stateName = stateName;
        this.listOfLanguages = new LanguageData[] { new LanguageData(lang1, spkr1), new LanguageData(lang2, spkr2),
                new LanguageData(lang3, spkr3) };
    }

    /**
     * Constructs a Value with a state name and an array of language/speaker pairs.
     *
     * @param stateName the name of the state
     * @param inits     array of alternating language names and speaker counts
     */
    public Value(String stateName, String[] inits) {
        this.stateName = stateName;
        if (inits.length < 2) {
            throw new IllegalArgumentException("At least one language and its speaker count must be provided.");
        }

        this.listOfLanguages = new LanguageData[(int) Math.rint(inits.length / 2.0f)];
        for (int i = 0; i < listOfLanguages.length; i++) {
            String lang = inits[i * 2];
            int spkr = (int) Double.parseDouble(inits[i * 2 + 1]);
            listOfLanguages[i] = new LanguageData(lang, spkr);
        }
    }

    /**
     * Returns a string representation of the value, including state and dialects.
     *
     * @return string representation
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        for (LanguageData lang : listOfLanguages)
            if (lang.getName() != null)
                sb.append(lang.toString()).append(", ");
        return "\t" + "State: " + stateName + ", Dialects: " + sb.toString();
    }
}
