package HashiPuzzle;

import javax.swing.SwingUtilities;

/**
 * Entry point for the Hashi puzzle visualizer application.
 *
 * <p>
 * Prompts the user to select a puzzle input file, parses it into a {@link Map},
 * validates the puzzle state using {@link Hashier#isSolution(Map)}, and
 * displays the result in a {@link PuzzleFrame} with visual feedback.
 *
 * @author AfrazSohail
 * @note Javadoc documentation generated by AI; original logic by AfrazSohail
 */
public class Driver {

    /**
     * Runs the puzzle visualizer.
     *
     * @param args unused; the user selects a file via a file chooser dialog
     */
    public static void main(String[] args) {
        String text = FileReader.openFile();
        if (text == null) {
            return;
        }

        Map map = new Map(text);
        boolean isSolution = Hashier.isSolution(map);
        System.out.println(isSolution);
        SwingUtilities.invokeLater(() -> new PuzzleFrame(map, isSolution));
    }
}
