package HashiPuzzle;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 * Top-level window that displays a Hashi puzzle.
 *
 * <p>
 * The grid is rendered by {@link PuzzlePanel} in a scroll pane, and a colour
 * status bar at the bottom reports whether the current state is a valid
 * solution. The frame has no interactive controls; it is purely a display
 * component.
 *
 * @author AfrazSohail
 * @note Documentation generated by AI
 * @see PuzzlePanel
 * @see Map
 */
public class PuzzleFrame extends JFrame {

    /**
     * Constructs a {@code PuzzleFrame} that displays the given puzzle.
     *
     * @param map the Hashi puzzle map to display
     * @param isSolution {@code true} if the puzzle state is a valid solution,
     * {@code false} otherwise
     */
    public PuzzleFrame(Map map, boolean isSolution) {
        super("Hashi Puzzle");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        add(new JScrollPane(new PuzzlePanel(map)), BorderLayout.CENTER);
        add(buildStatusBar(isSolution), BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Builds and returns the status bar label.
     *
     * <p>
     * Displays "Valid solution!" in green if the puzzle is solved, or "Not a
     * valid solution." in red otherwise.
     *
     * @param isSolution {@code true} if the puzzle is solved
     * @return the configured {@link JLabel} to display as a status bar
     */
    private JLabel buildStatusBar(boolean isSolution) {
        String text = isSolution ? "Valid solution!" : "Not a valid solution.";
        Color color = isSolution ? new Color(0, 140, 0) : new Color(190, 0, 0);

        JLabel label = new JLabel(text, SwingConstants.CENTER);
        label.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 15));
        label.setForeground(color);
        label.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        return label;
    }
}
