
/**
 * NavigationLab - A route planning and optimization system
 *
 * This class represents a location in a 2D coordinate system with a name and
 * coordinates.
 * Locations can be linked together to form routes using a linked list
 * structure.
 *
 * @author Afraz Sohail
 * @version final
 * @since 1.0
 *
 *        Javadoc documentation generated by Claude Sonnet 4
 */
public class Location {
    /** The name identifier for this location */
    String name;
    /** The x-coordinate of this location */
    double x;
    /** The y-coordinate of this location */
    double y;
    /** Reference to the next location in the linked list structure */
    Location next;

    /**
     * Constructs a new Location with specified coordinates and name.
     *
     * @param name The name identifier for this location
     * @param x    The x-coordinate of this location
     * @param y    The y-coordinate of this location
     * @param next Reference to the next location in the linked list, or null if
     *             this is the last location
     */
    public Location(String name, double x, double y, Location next) {
        this.name = name;
        this.x = x;
        this.y = y;
        this.next = next;
    }

    /**
     * Constructs a new Location with specified coordinates and name.
     * The next location is set to null.
     *
     * @param name The name identifier for this location
     * @param x    The x-coordinate of this location
     * @param y    The y-coordinate of this location
     */
    public Location(String name, double x, double y) {
        this(name, x, y, null);
    }

    /**
     * Calculates the Euclidean distance between this location and another location.
     * Uses the distance formula: sqrt((x2-x1)² + (y2-y1)²)
     *
     * @param other The other location to calculate distance to
     * @return The Euclidean distance between the two locations
     * @throws NullPointerException if other is null
     */
    public double distanceTo(Location other) {
        return Math.sqrt(Math.pow(this.x - other.x, 2) + Math.pow(this.y - other.y, 2));
    }
}
