
package Classwork.Unit3.CustomHashmap;

/*
 * CustomHashmap.java
 *
 * This file is part of the CustomHashmap project for educational purposes.
 *
 * Provides a custom implementation of a hash map data structure with chaining for collision resolution.
 * Includes dynamic resizing (rehashing) based on load factors, and supports basic operations such as put, get, and remove.
 *
 * Project documentation and code comments generated by AI (GitHub Copilot) on November 16, 2025.
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import Classwork.Unit3.CustomHashmap.KEV.*;

/**
 * CustomHashmap is a custom implementation of a hash map data structure using
 * chaining for collision resolution.
 * <p>
 * Features:
 * <ul>
 * <li>Dynamic resizing (rehashing) based on load factors</li>
 * <li>Supports put, get, and remove operations</li>
 * <li>Tracks collision rate</li>
 * <li>Can load entries from a file</li>
 * </ul>
 * <p>
 * Documentation generated by AI (GitHub Copilot).
 */
public class CustomHashmap {
    /**
     * Array of Entry objects representing the hash table buckets.
     */
    Entry[] census;

    /**
     * Number of entries currently in the hash map.
     */
    public int size;

    /**
     * Tracks the number of collisions that have occurred.
     */
    private int collisionRate;

    /**
     * Scanner for user input (used for error handling).
     */
    Scanner scanner = new Scanner(System.in);

    /**
     * Returns the collision rate as a percentage of total entries.
     *
     * @return collision rate percentage
     */
    public int getCollisionRate() {
        return (size == 0) ? 0 : collisionRate * 100 / size;
    }

    /**
     * Maximum load factor before rehashing (expanding) the table.
     */
    public static final double MAXLOAD = 0.75d;

    /**
     * Minimum load factor before rehashing (shrinking) the table.
     */
    public static final double MINLOAD = 0.10d;

    /**
     * Constructs an empty CustomHashmap with an initial capacity of 11.
     */
    public CustomHashmap() {
        census = new Entry[11];
        size = 0;
        collisionRate = 0;
    }

    /**
     * Inserts a new entry into the hash map.
     *
     * @param newEntry the entry to insert
     * @return the previous value associated with the key, or null if none
     */
    public Value put(Entry newEntry) {
        if (newEntry == null) {
            GUI.errorInvalidFormat();
            scanner.nextLine();
            GUI.clearConsole();
            return null;
        }

        int index = newEntry.key.hashCode() % census.length;
        return put(index, newEntry);
    }

    /**
     * Inserts a new entry at a specific index in the hash table.
     * Handles collisions using chaining.
     *
     * @param index    the index to insert at
     * @param newEntry the entry to insert
     * @return the previous value associated with the key, or null if none
     */
    public Value put(int index, Entry newEntry) {
        if (newEntry == null) {
            GUI.errorInvalidFormat();
            scanner.nextLine();
            GUI.clearConsole();
            return null;
        }

        if (census[index] == null) {
            size++;
            census[index] = newEntry;

            if ((double) size / census.length >= MAXLOAD)
                rehash();

            GUI.putEntry(newEntry, null);
            return null;
        } else {
            collisionRate++;
            System.out.println("Collision occurred at index " + index + " for key " + newEntry.key);

            Entry curEntry = census[index];
            while (curEntry != null) {
                if (curEntry.key.equals(newEntry.key)) {
                    Value temp = curEntry.value.getClone();

                    newEntry.next = curEntry.next;
                    newEntry.prev = curEntry.prev;

                    if (newEntry.next != null)
                        newEntry.next.prev = newEntry;
                    if (newEntry.prev != null)
                        newEntry.prev.next = newEntry;
                    else
                        census[index] = newEntry;

                    GUI.putEntry(newEntry, temp);
                    return temp;
                }
                if (curEntry.next == null)
                    break;
                curEntry = curEntry.next;
            }

            curEntry.next = newEntry;
            newEntry.prev = curEntry;

            GUI.putEntry(newEntry, null);
            return null;
        }
    }

    /**
     * Retrieves the value associated with the given key.
     *
     * @param key the key to search for
     * @return the value associated with the key, or null if not found
     */
    public Value get(Key key) {
        if (key == null) {
            GUI.errorInvalidFormat();
            scanner.nextLine();
            GUI.clearConsole();
            return null;
        }

        int index = key.hashCode() % census.length;
        Entry curEntry = census[index];

        while (curEntry != null) {
            if (curEntry.key.equals(key)) {
                GUI.getEntry(curEntry);
                return curEntry.value;
            }
            curEntry = curEntry.next;
        }

        GUI.errorInvalidFormat();
        scanner.nextLine();
        GUI.clearConsole();
        return null;
    }

    /**
     * Removes the entry associated with the given key from the hash map.
     *
     * @param key the key to remove
     * @return the value that was removed, or null if not found
     */
    public Value remove(Key key) {
        int index = key.hashCode() % census.length;
        Entry curEntry = census[index];

        while (curEntry != null) {
            if (curEntry.key.equals(key)) {
                Value tempValue = curEntry.value;

                // If it's the first entry in the bucket
                if (curEntry.prev == null) {
                    census[index] = curEntry.next;
                    if (curEntry.next != null)
                        curEntry.next.prev = null;
                } else {
                    // It's in the middle or end of the chain
                    curEntry.prev.next = curEntry.next;
                    if (curEntry.next != null)
                        curEntry.next.prev = curEntry.prev;
                }

                size--;
                if ((double) size / census.length <= MINLOAD)
                    rehash();

                GUI.removeEntry(curEntry);
                return tempValue;
            }
            curEntry = curEntry.next;
        }

        GUI.errorInvalidFormat();
        scanner.nextLine();
        GUI.clearConsole();
        return null;
    }

    /**
     * Rehashes the hash table to a new size based on the current load factor.
     * Expands or shrinks the table as needed.
     */
    private void rehash() {
        int newSize = census.length;
        if ((double) size / census.length >= MAXLOAD) {
            System.out.println("Maximum Load Factor Exceeded, REHASHING!");
            newSize = census.length * 2;
        } else if ((double) size / census.length <= MINLOAD && census.length > 11) {
            System.out.println("Minimum Load Factor Undercut, REHASHING!");
            newSize = Math.max(11, census.length / 2);
        }

        Entry[] newCensus = new Entry[newSize];
        CustomHashmap newCustomHashmap = new CustomHashmap();
        newCustomHashmap.census = newCensus;

        for (Entry entry : census) {
            while (entry != null) {
                Entry nextEntry = entry.next;
                entry.next = null;
                entry.prev = null;
                newCustomHashmap.put(entry);
                entry = nextEntry;
            }
        }
        this.size = newCustomHashmap.size;
        this.collisionRate = newCustomHashmap.collisionRate;
        this.census = newCustomHashmap.census;
    }

    /**
     * Returns a string representation of the hash map, including all entries, load
     * factor, and collision rate.
     *
     * @return string representation of the hash map
     */
    public String toString() {
        String output = "";
        for (Entry entry : census)
            while (entry != null) {
                output += entry + "\n";
                entry = entry.next;
            }
        output += "Load Factor: " + MAXLOAD + ", Current Load: " + size + " / " + census.length + "\n";
        output += "Collision Rate: " + getCollisionRate() + "%\n";
        return output;
    }

    /**
     * Loads entries from a file and inserts them into the hash map.
     * Each line in the file should be formatted as: key,number,value,...
     *
     * @param file the file to load from
     * @throws FileNotFoundException if the file cannot be found
     */
    public void loadFromFile(File file) throws FileNotFoundException {
        Scanner fileScanner = new Scanner(file);

        while (fileScanner.hasNextLine()) {
            String line = fileScanner.nextLine();
            String[] parts = line.split(",");

            if (parts.length < 3) {
                continue;
            }

            Key key = new Key(parts[0], Integer.parseInt(parts[1]));
            Value value = new Value(parts[2], Arrays.copyOfRange(parts, 3, parts.length));

            Entry entry = new Entry(key, value);
            put(entry);
        }

        fileScanner.close();
    }

    /**
     * Returns a string describing the current load factor and table size.
     *
     * @return load factor description
     */
    public String loadFactor() {
        return "Load Factor: " + MAXLOAD + ", Current Load: " + size + " / " + census.length;
    }
}
