package Classwork.Unit3.CustomHashmap;

/*
 * Driver.java
 *
 * Main driver for the CustomHashmap project. Handles user interaction, menu navigation,
 * and file operations for loading, inserting, retrieving, and removing entries.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.io.File;
import java.io.FileNotFoundException;
import Classwork.Unit3.CustomHashmap.KEV.*;

/**
 * Driver class for the CustomHashmap project. Provides a console-based
 * interface for interacting with the hash map.
 */
public class Driver {
    /**
     * The main CustomHashmap instance used by the program.
     */
    static CustomHashmap customHashmap = new CustomHashmap();

    /**
     * Scanner for user input.
     */
    static Scanner scanner = new Scanner(System.in);

    /**
     * Main method. Displays the menu and handles user choices.
     *
     * @param args command-line arguments
     */
    public static void main(String args[]) {
        GUI.title();
        scanner.nextLine();
        GUI.clearConsole();

        boolean exit = false;
        while (!exit) {
            GUI.menu();
            String answer = scanner.nextLine();
            GUI.clearConsole();
            if (answer.isEmpty())
                continue;

            switch (answer) {
                case "1":
                    chooseFileCSV();
                    break;
                case "2":
                    putEntry();
                    break;
                case "3":
                    getEntry();
                    break;
                case "4":
                    removeEntry();
                    break;
                case "5":
                    System.out.println(customHashmap.toString());
                    System.out.println("Press Enter to continue...");
                    scanner.nextLine();
                    break;
                case "6":
                    exit = true;
                    break;
                default:
                    break;
            }
        }
    }

    /**
     * Handles file selection and loading entries from a CSV file.
     */
    private static void chooseFileCSV() {
        GUI.chooseFileCSV();
        scanner.nextLine();
        GUI.clearConsole();

        final File[] selectedFile = new File[1];
        try {
            SwingUtilities.invokeAndWait(() -> {
                JFrame frame = new JFrame();
                frame.setAlwaysOnTop(true);

                JFileChooser file = new JFileChooser(new File(System.getProperty("user.dir")));
                file.setDialogTitle("Select CSV File");

                int code = file.showOpenDialog(frame);
                if (code == JFileChooser.APPROVE_OPTION) {
                    selectedFile[0] = file.getSelectedFile();
                }

                frame.dispose();
            });

            if (selectedFile[0] != null) {
                System.out.println("You selected: " + selectedFile[0].getAbsolutePath());
                try {
                    customHashmap.loadFromFile(selectedFile[0]);
                    GUI.fileSelected();
                    System.out.print(selectedFile[0].getAbsolutePath());
                    scanner.nextLine();
                    GUI.clearConsole();
                } catch (FileNotFoundException e) {
                    GUI.errorFileNotFound();
                    scanner.nextLine();
                    GUI.clearConsole();
                }
            } else {
                GUI.fileNotSelected();
                scanner.nextLine();
                GUI.clearConsole();
            }
        } catch (Exception e) {
            GUI.errorFileChooser();
            scanner.nextLine();
            GUI.clearConsole();
        }

        GUI.fileSelectedReport(customHashmap.getCollisionRate());
        scanner.nextLine();
        GUI.clearConsole();
    }

    /**
     * Handles user input for inserting a new entry into the hash map.
     */
    private static void putEntry() {
        GUI.enterStateName();
        String stateName = scanner.nextLine().trim();
        GUI.clearConsole();

        GUI.enterLangSpkr();
        String langSpkrInput[] = scanner.nextLine().trim().split(",");
        GUI.clearConsole();

        GUI.withIndexOrNot();
        String answer = scanner.nextLine().toLowerCase().trim();
        GUI.clearConsole();

        switch (answer) {
            case "y":
                GUI.enterIndexNameCode();
                String indexNameCode[] = scanner.nextLine().trim().split(",");
                GUI.clearConsole();
                if (indexNameCode.length < 3) {
                    GUI.errorInvalidFormat();
                    scanner.nextLine();
                    GUI.clearConsole();
                    return;
                }

                Key key = new Key(indexNameCode[1].trim(), Integer.parseInt(indexNameCode[2].trim()));
                Value value = new Value(stateName, langSpkrInput);
                Entry entry = new Entry(key, value);

                customHashmap.put(Integer.parseInt(indexNameCode[0].trim()), entry);
                break;
            case "n":
                GUI.enterNameCode();
                String nameCode[] = scanner.nextLine().trim().split(",");
                GUI.clearConsole();
                if (nameCode.length < 2) {
                    GUI.errorInvalidFormat();
                    scanner.nextLine();
                    GUI.clearConsole();
                    return;
                }

                key = new Key(nameCode[0].trim(), Integer.parseInt(nameCode[1].trim()));
                value = new Value(stateName, langSpkrInput);
                entry = new Entry(key, value);

                customHashmap.put(entry);
                break;
            default:
                break;
        }
    }

    /**
     * Handles user input for retrieving an entry from the hash map.
     */
    public static void getEntry() {
        GUI.enterNameCode();
        String nameCode[] = scanner.nextLine().trim().split(",");
        GUI.clearConsole();
        if (nameCode.length < 2) {
            GUI.errorInvalidFormat();
            scanner.nextLine();
            GUI.clearConsole();
            return;
        }

        Key key = new Key(nameCode[0].trim(), Integer.parseInt(nameCode[1].trim()));
        customHashmap.get(key);
    }

    /**
     * Handles user input for removing an entry from the hash map.
     */
    public static void removeEntry() {
        GUI.enterNameCode();
        String nameCode[] = scanner.nextLine().trim().split(",");
        GUI.clearConsole();
        if (nameCode.length < 2) {
            GUI.errorInvalidFormat();
            scanner.nextLine();
            GUI.clearConsole();
            return;
        }

        Key key = new Key(nameCode[0].trim(), Integer.parseInt(nameCode[1].trim()));
        customHashmap.remove(key);
    }
}
