package Classwork.Unit3.CustomHashmap;
/*
 * GUI.java
 *
 * Provides console-based graphical user interface elements for the CustomHashmap project.
 * Contains methods for displaying menus, prompts, error messages, and formatted output.
 *
 * Documentation generated by AI (GitHub Copilot) on November 16, 2025.
 */

import Classwork.Unit3.CustomHashmap.KEV.*;

/**
 * GUI class provides static methods for displaying console-based interface
 * elements
 * for the CustomHashmap application, including menus, prompts, and formatted
 * messages.
 */
public class GUI {
    /**
     * Displays the title screen with ASCII art logo.
     */
    public static void title() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║    ██████╗██╗   ██╗███████╗████████╗ ██████╗ ███╗   ███╗       ║\n");
        page.append("║   ██╔════╝██║   ██║██╔════╝╚══██╔══╝██╔═══██╗████╗ ████║       ║\n");
        page.append("║   ██║     ██║   ██║███████╗   ██║   ██║   ██║██╔████╔██║       ║\n");
        page.append("║   ██║     ██║   ██║╚════██║   ██║   ██║   ██║██║╚██╔╝██║       ║\n");
        page.append("║   ╚██████╗╚██████╔╝███████║   ██║   ╚██████╔╝██║ ╚═╝ ██║       ║\n");
        page.append("║    ╚═════╝ ╚═════╝ ╚══════╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝       ║\n");
        page.append("║                                                                ║\n");
        page.append("║   ██╗  ██╗ █████╗ ███████╗██╗  ██╗███╗   ███╗ █████╗ ██████╗   ║\n");
        page.append("║   ██║  ██║██╔══██╗██╔════╝██║  ██║████╗ ████║██╔══██╗██╔══██║  ║\n");
        page.append("║   ███████║███████║███████╗███████║██╔████╔██║███████║██████╔╝  ║\n");
        page.append("║   ██╔══██║██╔══██║╚════██║██╔══██║██║╚██╔╝██║██╔══██║██╔═══╝   ║\n");
        page.append("║   ██║  ██║██║  ██║███████║██║  ██║██║ ╚═╝ ██║██║  ██║██║       ║\n");
        page.append("║   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝       ║\n");
        page.append("║                                                                ║\n");
        page.append("║              Data Structures & Algorithms Project              ║\n");
        page.append("║                     Press Enter to continue                    ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays the main menu with available options.
     */
    public static void menu() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║             ███╗   ███╗███████╗███╗   ██╗██╗   ██╗             ║\n");
        page.append("║             ████╗ ████║██╔════╝████╗  ██║██║   ██║             ║\n");
        page.append("║             ██╔████╔██║█████╗  ██╔██╗ ██║██║   ██║             ║\n");
        page.append("║             ██║╚██╔╝██║██╔══╝  ██║╚██╗██║██║   ██║             ║\n");
        page.append("║             ██║ ╚═╝ ██║███████╗██║ ╚████║╚██████╔╝             ║\n");
        page.append("║             ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝              ║\n");
        page.append("║                                                                ║\n");
        page.append("╠════════════════════════════════════════════════════════════════╣\n");
        page.append("║                                                                ║\n");
        page.append("║   [1] Choose File (CSV)                                        ║\n");
        page.append("║   [2] Put Entry                                                ║\n");
        page.append("║   [3] Get Entry                                                ║\n");
        page.append("║   [4] Remove Entry                                             ║\n");
        page.append("║   [5] Display Hashmap Statistics                               ║\n");
        page.append("║   [6] Exit                                                     ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");
        page.append("Enter your choice: ");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt to choose a CSV file.
     */
    public static void chooseFileCSV() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                   Choose a CSV File to Load                    ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a success message when a file is selected.
     */
    public static void fileSelected() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                   File Successfully Selected                   ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a message when no file was selected.
     */
    public static void fileNotSelected() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                      No File Was Selected                      ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays an error message when a file is not found.
     */
    public static void errorFileNotFound() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                      ERROR: File Not Found                     ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");
    }

    /**
     * Displays an error message when the file chooser encounters an issue.
     */
    public static void errorFileChooser() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                  ERROR: File Chooser Issue                     ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a report after a file is loaded, showing the collision rate.
     *
     * @param collisionRate the collision rate percentage
     */
    public static void fileSelectedReport(int collisionRate) {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔═════════════════════════FILE═LOADED════════════════════════════╗\n");
        page.append("║ Initial Collision Rate: " + collisionRate + "%\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());

    }

    /**
     * Displays an error message for invalid input format.
     */
    public static void errorInvalidFormat() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                     ERROR: Invalid Format                      ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt to enter district name and code.
     */
    public static void enterNameCode() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                  ENTER District Name and Code                  ║\n");
        page.append("║                   <Dist. Name>, <Dist. Code>                   ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt to enter index, district name, and code.
     */
    public static void enterIndexNameCode() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║              ENTER Index, District Name and Code               ║\n");
        page.append("║               <Index>, <Dist. Name>, <Dist. Code>              ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt to enter the state name for an entry.
     */
    public static void enterStateName() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                   ENTER State Name for Entry                   ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt to enter language and speaker count (up to 3 languages).
     */
    public static void enterLangSpkr() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║           ENTER Language and Speaker Count (up to 3)           ║\n");
        page.append("║                      <Lang1>, <Spkr1>,...                      ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a prompt asking whether the user wants to provide an index.
     */
    public static void withIndexOrNot() {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔════════════════════════════════════════════════════════════════╗\n");
        page.append("║                                                                ║\n");
        page.append("║                Do you want to provide an Index?                ║\n");
        page.append("║                     [Y] Yes         [N] No                     ║\n");
        page.append("║                                                                ║\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays a confirmation message after putting an entry into the hash map.
     *
     * @param newEntry  the entry that was added
     * @param prevValue the previous value if the key already existed, null
     *                  otherwise
     */
    public static void putEntry(Entry newEntry, Value prevValue) {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔═════════════════════════FILE═LOADED════════════════════════════╗\n");
        page.append("║ Put " + newEntry.toString() + "\n");
        if (prevValue != null)
            page.append("║ Replaced Previous Value: " + prevValue.toString() + "\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays the retrieved entry from the hash map.
     *
     * @param entry the entry that was retrieved
     */
    public static void getEntry(Entry entry) {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔═════════════════════════GET═ENTRY══════════════════════════════╗\n");
        page.append("║ Retrieved " + entry.toString() + "\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Displays the removed entry from the hash map.
     *
     * @param entry the entry that was removed
     */
    public static void removeEntry(Entry entry) {
        StringBuilder page = new StringBuilder();

        page.append("\n");
        page.append("╔═════════════════════════REMOVE═ENTRY═══════════════════════════╗\n");
        page.append("║ Removed " + entry.toString() + "\n");
        page.append("╚════════════════════════════════════════════════════════════════╝\n");

        System.out.println(page.toString());
    }

    /**
     * Clears the console screen.
     * Works on both Windows (using cmd cls) and Unix-like systems (using ANSI
     * escape codes).
     * Method implementation generated by AI (GitHub Copilot).
     */
    public static void clearConsole() {
        try {
            if (System.getProperty("os.name").contains("Windows")) {
                new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
            } else {
                System.out.print("\033[H\033[2J");
                System.out.flush();
            }
        } catch (Exception e) {
            System.out.println("Error clearing console: " + e.getMessage());
        }
    }
}
